// Mock data for demo purposes - shows UI without backend connection
import { Movie, TvShow, Rating, WatchlistItem } from './types';

export const TRENDING_MOVIES: Movie[] = [
  {
    id: 533535,
    title: "Deadpool & Wolverine",
    year: 2024,
    poster: "https://image.tmdb.org/t/p/w500/8cdWjvZQUExUUTzyp4t6EDMubfO.jpg",
    lang: "en",
    genres: ["Action", "Comedy", "Superhero"],
    matchScore: 95,
    matchReason: "Based on your love for Marvel movies",
  },
  {
    id: 1184918,
    title: "The Wild Robot",
    year: 2024,
    poster: "https://image.tmdb.org/t/p/w500/wTnV3PCVW5O92JMrFvvrRcV39RU.jpg",
    lang: "en",
    genres: ["Animation", "Adventure", "Family"],
    matchScore: 88,
    matchReason: "You enjoyed animated features",
  },
  {
    id: 912649,
    title: "Venom: The Last Dance",
    year: 2024,
    poster: "https://image.tmdb.org/t/p/w500/aosm8NMQ3UyoBVpSxyimorCQykC.jpg",
    lang: "en",
    genres: ["Action", "Science Fiction"],
    matchScore: 82,
    matchReason: "Similar to Spider-Man films you rated",
  },
  {
    id: 1034541,
    title: "Terrifier 3",
    year: 2024,
    poster: "https://image.tmdb.org/t/p/w500/7NDHoebflLwL1CcgLJ2CjLTqiEO.jpg",
    lang: "en",
    genres: ["Horror", "Thriller"],
    matchScore: 75,
    matchReason: "Horror genre preference",
  },
  {
    id: 698687,
    title: "Transformers One",
    year: 2024,
    poster: "https://image.tmdb.org/t/p/w500/qbkAqmmEIZfrCO8ZQAuIuVMlWoV.jpg",
    lang: "en",
    genres: ["Animation", "Action", "Adventure"],
    matchScore: 79,
    matchReason: "Matches your action preferences",
  },
  {
    id: 957452,
    title: "The Crow",
    year: 2024,
    poster: "https://image.tmdb.org/t/p/w500/58QT4cPJ2u2TqWZkterDq9q4yxQ.jpg",
    lang: "en",
    genres: ["Action", "Fantasy", "Horror"],
    matchScore: 72,
    matchReason: "Dark fantasy genre match",
  },
  {
    id: 1022789,
    title: "Inside Out 2",
    year: 2024,
    poster: "https://image.tmdb.org/t/p/w500/vpnVM9B6NMmQpWeZvzLvDESb2QY.jpg",
    lang: "en",
    genres: ["Animation", "Family", "Comedy"],
    matchScore: 91,
    matchReason: "You loved the original Inside Out",
  },
  {
    id: 693134,
    title: "Dune: Part Two",
    year: 2024,
    poster: "https://image.tmdb.org/t/p/w500/8b8R8l88Qje9dn9OE8PY05Nxl1X.jpg",
    lang: "en",
    genres: ["Science Fiction", "Adventure"],
    matchScore: 94,
    matchReason: "Epic sci-fi matches your taste",
  },
];

export const TRENDING_TVSHOWS: TvShow[] = [
  {
    id: 94997,
    name: "House of the Dragon",
    title: "House of the Dragon",
    year: 2022,
    poster: "https://image.tmdb.org/t/p/w500/t9XkeE7HzOsdQcDDDapDYh8Rrmt.jpg",
    lang: "en",
    genres: ["Drama", "Fantasy"],
  },
  {
    id: 84773,
    name: "The Lord of the Rings: The Rings of Power",
    title: "The Lord of the Rings: The Rings of Power",
    year: 2022,
    poster: "https://image.tmdb.org/t/p/w500/mYLOqiStMxDK3fYZFirgrMt8z5d.jpg",
    lang: "en",
    genres: ["Drama", "Fantasy", "Action"],
  },
  {
    id: 1399,
    name: "Game of Thrones",
    title: "Game of Thrones",
    year: 2011,
    poster: "https://image.tmdb.org/t/p/w500/1XS1oqL89opfnbLl8WnZY1O1uJx.jpg",
    lang: "en",
    genres: ["Drama", "Fantasy"],
  },
  {
    id: 76479,
    name: "The Boys",
    title: "The Boys",
    year: 2019,
    poster: "https://image.tmdb.org/t/p/w500/stTEycfG9928HYGEISBFaG1ngjM.jpg",
    lang: "en",
    genres: ["Action", "Comedy", "Crime"],
  },
  {
    id: 1396,
    name: "Breaking Bad",
    title: "Breaking Bad",
    year: 2008,
    poster: "https://image.tmdb.org/t/p/w500/ztkUQFLlC19CCMYHW9o1zWhJRNq.jpg",
    lang: "en",
    genres: ["Drama", "Crime", "Thriller"],
  },
  {
    id: 66732,
    name: "Stranger Things",
    title: "Stranger Things",
    year: 2016,
    poster: "https://image.tmdb.org/t/p/w500/49WJfeN0moxb9IPfGn8AIqMGskD.jpg",
    lang: "en",
    genres: ["Drama", "Mystery", "Sci-Fi"],
  },
];

export const MOVIES_TO_RATE: Movie[] = [
  {
    id: 27205,
    title: "Inception",
    year: 2010,
    poster: "https://image.tmdb.org/t/p/w500/oYuLEt3zVCKq57qu2F8dT7NIa6f.jpg",
    lang: "en",
    genres: ["Action", "Sci-Fi", "Thriller"],
    description: "A thief who steals corporate secrets through dream-sharing technology is given the inverse task of planting an idea into the mind of a C.E.O.",
  },
  {
    id: 155,
    title: "The Dark Knight",
    year: 2008,
    poster: "https://image.tmdb.org/t/p/w500/qJ2tW6WMUDux911r6m7haRef0WH.jpg",
    lang: "en",
    genres: ["Action", "Crime", "Drama"],
    description: "When the menace known as the Joker wreaks havoc on Gotham, Batman must accept one of the greatest psychological tests of his ability to fight injustice.",
  },
  {
    id: 238,
    title: "The Godfather",
    year: 1972,
    poster: "https://image.tmdb.org/t/p/w500/3bhkrj58Vtu7enYsRolD1fZdja1.jpg",
    lang: "en",
    genres: ["Crime", "Drama"],
    description: "The aging patriarch of an organized crime dynasty transfers control of his clandestine empire to his reluctant youngest son.",
  },
  {
    id: 680,
    title: "Pulp Fiction",
    year: 1994,
    poster: "https://image.tmdb.org/t/p/w500/d5iIlFn5s0ImszYzBPb8JPIfbXD.jpg",
    lang: "en",
    genres: ["Crime", "Thriller"],
    description: "The lives of two mob hitmen, a boxer, a gangster and his wife intertwine in four tales of violence and redemption.",
  },
  {
    id: 550,
    title: "Fight Club",
    year: 1999,
    poster: "https://image.tmdb.org/t/p/w500/pB8BM7pdSp6B6Ih7QZ4DrQ3PmJK.jpg",
    lang: "en",
    genres: ["Drama", "Thriller"],
    description: "An insomniac office worker and a devil-may-care soap maker form an underground fight club.",
  },
  {
    id: 13,
    title: "Forrest Gump",
    year: 1994,
    poster: "https://image.tmdb.org/t/p/w500/arw2vcBveWOVZr6pxd9XTd1TdQa.jpg",
    lang: "en",
    genres: ["Comedy", "Drama", "Romance"],
    description: "The presidencies of Kennedy and Johnson, the Vietnam War, and other historical events unfold from the perspective of an Alabama man.",
  },
  {
    id: 122,
    title: "The Lord of the Rings: The Return of the King",
    year: 2003,
    poster: "https://image.tmdb.org/t/p/w500/rCzpDGLbOoPwLjy3OAm5NUPOTrC.jpg",
    lang: "en",
    genres: ["Adventure", "Fantasy", "Action"],
    description: "Gandalf and Aragorn lead the World of Men against Sauron's army to draw his gaze from Frodo and Sam.",
  },
  {
    id: 157336,
    title: "Interstellar",
    year: 2014,
    poster: "https://image.tmdb.org/t/p/w500/gEU2QniE6E77NI6lCU6MxlNBvIx.jpg",
    lang: "en",
    genres: ["Adventure", "Drama", "Sci-Fi"],
    description: "A team of explorers travel through a wormhole in space in an attempt to ensure humanity's survival.",
  },
  {
    id: 603,
    title: "The Matrix",
    year: 1999,
    poster: "https://image.tmdb.org/t/p/w500/f89U3ADr1oiB1s9GkdPOEpXUk5H.jpg",
    lang: "en",
    genres: ["Action", "Sci-Fi"],
    description: "A computer hacker learns about the true nature of reality and his role in the war against its controllers.",
  },
  {
    id: 424,
    title: "Schindler's List",
    year: 1993,
    poster: "https://image.tmdb.org/t/p/w500/sF1U4EUQS8YHUYjNl3pMGNIQyr0.jpg",
    lang: "en",
    genres: ["Drama", "History", "War"],
    description: "In German-occupied Poland during World War II, Oskar Schindler becomes concerned for his Jewish workforce.",
  },
];

export const TVSHOWS_TO_RATE: TvShow[] = [
  {
    id: 94997,
    name: "House of the Dragon",
    title: "House of the Dragon",
    year: 2022,
    poster: "https://image.tmdb.org/t/p/w500/t9XkeE7HzOsdQcDDDapDYh8Rrmt.jpg",
    lang: "en",
    genres: ["Drama", "Fantasy"],
    description: "The Targaryen dynasty is at the height of its power, with more than 15 dragons under their yoke.",
  },
  {
    id: 76479,
    name: "The Boys",
    title: "The Boys",
    year: 2019,
    poster: "https://image.tmdb.org/t/p/w500/stTEycfG9928HYGEISBFaG1ngjM.jpg",
    lang: "en",
    genres: ["Action", "Comedy", "Crime"],
    description: "A group of vigilantes set out to take down corrupt superheroes who abuse their powers.",
  },
  {
    id: 1396,
    name: "Breaking Bad",
    title: "Breaking Bad",
    year: 2008,
    poster: "https://image.tmdb.org/t/p/w500/ztkUQFLlC19CCMYHW9o1zWhJRNq.jpg",
    lang: "en",
    genres: ["Drama", "Crime", "Thriller"],
    description: "A high school chemistry teacher turned methamphetamine producer partners with a former student.",
  },
  {
    id: 66732,
    name: "Stranger Things",
    title: "Stranger Things",
    year: 2016,
    poster: "https://image.tmdb.org/t/p/w500/49WJfeN0moxb9IPfGn8AIqMGskD.jpg",
    lang: "en",
    genres: ["Drama", "Mystery", "Sci-Fi"],
    description: "When a young boy vanishes, a small town uncovers a mystery involving secret experiments.",
  },
  {
    id: 1399,
    name: "Game of Thrones",
    title: "Game of Thrones",
    year: 2011,
    poster: "https://image.tmdb.org/t/p/w500/1XS1oqL89opfnbLl8WnZY1O1uJx.jpg",
    lang: "en",
    genres: ["Drama", "Fantasy"],
    description: "Nine noble families fight for control over the lands of Westeros.",
  },
  {
    id: 84773,
    name: "The Lord of the Rings: The Rings of Power",
    title: "The Lord of the Rings: The Rings of Power",
    year: 2022,
    poster: "https://image.tmdb.org/t/p/w500/mYLOqiStMxDK3fYZFirgrMt8z5d.jpg",
    lang: "en",
    genres: ["Drama", "Fantasy", "Action"],
    description: "Epic drama set thousands of years before the events of The Hobbit and The Lord of the Rings.",
  },
];

export const DEMO_USER = {
  id: 'demo-user',
  name: 'Demo User',
  email: 'demo@cinemate.app',
  image: null,
  languages: ['en', 'hi'],
  genres: ['Action', 'Sci-Fi', 'Drama'],
};

export const DEMO_RATINGS: Rating[] = [
  {
    id: '1',
    movieId: 27205,
    movieTitle: 'Inception',
    movieYear: 2010,
    rating: 'amazing',
    createdAt: new Date().toISOString(),
  },
  {
    id: '2',
    movieId: 155,
    movieTitle: 'The Dark Knight',
    movieYear: 2008,
    rating: 'amazing',
    createdAt: new Date().toISOString(),
  },
];

export const DEMO_WATCHLIST: WatchlistItem[] = [
  {
    id: '1',
    movieId: 693134,
    movieTitle: 'Dune: Part Two',
    movieYear: 2024,
    addedAt: new Date().toISOString(),
  },
  {
    id: '2',
    movieId: 1022789,
    movieTitle: 'Inside Out 2',
    movieYear: 2024,
    addedAt: new Date().toISOString(),
  },
];

